### ISSUE TITLE
Time management seems weird in Blitz games

### ISSUE THREAD

**Issue by Wikunia** [ArcticXWolf/AXWChessbot#7]
It seems like the engine takes roughly 30 seconds for each move in the early stages of a 3 minute Blitz game.
As an example: https://lichess.org/ZHIaQa1S 
Your bot was clearly winning as mine played some weird opening :smiley:

**Comment by ArcticXWolf** [comment]
Yeah, I noticed the game today. ^^

It was a regression from my implementation of mps timecontrol from #5 .
When confronted with a 0 increment, my engine thought it was not a fisher timecontrol game, but a game without timecontrol at all and defaulted to the maximum of 30 secs.

v0.0.9 fixes this and is already deployed on lichess.
